parameters:
  env: ''
  webserver: ''
jobs:
- job: A1
  variables: 
    - group: hangfiredashboard-${{parameters.env}}
    - name: webserverIp
      ${{ if eq( parameters.webserver, '01' )}}:
        value: $(webserverIp01)
      ${{ if eq( parameters.webserver, '02' )}}:
        value: $(webserverIp02)
    - name: webserverName
      ${{ if eq( parameters.webserver, '01' )}}:
        value: $(webserverName01)
      ${{ if eq( parameters.webserver, '02' )}}:
        value: $(webserverName02)
    - name: myEnv
      value: ${{parameters.env}}
  steps:
    - script: echo envname = $(myEnv)
    - script: echo deploying to ip $(webserverIp)
    - script: echo deploying to name $(webserverName)


#  - deployment: Deploy
#    displayName: Deploy
#    variables: 
#    - group: hangfiredashboard-${{parameters.env}}
#    - name: webserverIp
#      value: webserverIp${{parameters.webserver}}
#    - name: myEnv
#      value: ${{parameters.env}}
#    environment: 
#      name: jim
#      resourceType: VirtualMachine
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - checkout: self
#          - script: echo envname = $(myEnv)
#          - script: echo deploying to ip $(webserverIp)



