parameters:
  env: ''
  webserver: ''
jobs:
- job: A1
  variables: 
    - group: hangfiredashboard-${{parameters.env}}
    - name: webserverIp
      value: webserverIp${{parameters.webserver}}
    - name: myEnv
      value: ${{parameters.env}}
  steps:
    - script: echo envname = $(myEnv)
    - script: echo deploying to ip $(webserverIp)


#  - deployment: Deploy
#    displayName: Deploy
#    variables: 
#    - group: hangfiredashboard-${{parameters.env}}
#    - name: webserverIp
#      value: webserverIp${{parameters.webserver}}
#    - name: myEnv
#      value: ${{parameters.env}}
#    environment: 
#      name: jim
#      resourceType: VirtualMachine
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - checkout: self
#          - script: echo envname = $(myEnv)
#          - script: echo deploying to ip $(webserverIp)



