parameters:
  env: ''
  webserver: ''
jobs:
  - deployment: Deploy
    displayName: Deploy
    variables: 
    - group: hangfiredashboard-${{parameters.env}}
    - name: webserverIp
      value: webserverIp${{parameters.webserver}}
    - name: myEnv
      value: ${{parameters.env}}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: echo envname = $(myEnv)
          - script: echo deploying to ip $(webserverIp)



