# top level is the Stage - contains jobs

trigger: none

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
    - name: envname
      type: string
      displayName: Enter Parameter1 value
      
stages:
- stage: A
  displayName: Stage A
  pool:
    name: Default
 
  jobs:
  - job: A1
    steps:
    - script: echo step A1
    - script: echo ${envname}
    - script: echo $(envname)

- stage: B
  displayName: Stage B
  pool:
    name: Default
  jobs:
  - job: B1
    steps:
    - script: echo step   B1