# top level is the Stage - contains jobs
stages:
- stage: A
  displayName: Stage A
  pool:
    name: Default
 
  jobs:
    steps:
    - script: echo step   A1

- stage: B
  displayName: Stage B
  pool:
    name: Default
  jobs:
  - job: B1
    steps:
    - script: echo step   B1