# top level is the Stage - contains jobs

trigger: none

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: envname
  type: string
  displayName: Enter Parameter1 value
- name: webServer
  displayName: Web Server to release to
  type: string
  default: 01 # this should be remembered from last pipeline run
  values:
  - 01
  - 02      
      
stages:
- stage: A
  displayName: Stage A
  pool:
    name: Default

  variables:
  - group: variableGroup1
  - name: varTest1
    value: varTest1
  - name: varWebserverIpaddress
    value: $(webserverIpaddress)
 
  jobs:
  - job: A1
    steps:
    - script: echo step A1
    - script: echo envname = ${{parameters.envname}}
    - script: echo We are upgrading web server ${{parameters.webServer}}
    - script: echo test1 = $(varTest1)
    - script: echo varWebserverIpaddress =$(varWebserverIpaddress)
    - script: echo group webserveripaddress = $(webserverIpaddress)

- stage: B
  displayName: Stage B
  pool:
    name: Default
  jobs:
  - job: B1
    steps:
    - script: echo step   B1