# top level is the Stage - contains jobs

trigger: none

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
    - name: envname
      type: string
      displayName: Enter Parameter1 value
      
stages:
- stage: A
  displayName: Stage A
  pool:
    name: Default

  variables:
  - group: variableGroup1
  - name: test1
    value: test1
  - name: mywebserveripaddress
    value: ${{variables.webserveripaddress}}
 
  jobs:
  - job: A1
    steps:
    - script: echo step A1
    - script: echo envname = ${envname}
    - script: echo test1 = ${test1}
    - script: mywebserveripaddress =${mywebserveripaddress}
    - script: webserveripaddress = ${webserveripaddress}

- stage: B
  displayName: Stage B
  pool:
    name: Default
  jobs:
  - job: B1
    steps:
    - script: echo step   B1