trigger: none

pool:
  name: Default

parameters:
- name: webServer
  displayName: Web Server to release to
  type: string
  default: 01 # this should be remembered from last pipeline run
  values:
  - 01
  - 02   

stages:   
- stage: DeployUAT
  displayName: 'DeployUAT'

  jobs:   
  - template: templates\example.template.yml
    parameters:
      env: 'uat'
      webserver: ${{ parameters.webServer }}


